package com.escape.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.escape.model.ChurchMember;
import com.escape.model.ChurchMemberExample;

public interface ChurchMemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int countByExample(ChurchMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int deleteByExample(ChurchMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int insert(ChurchMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int insertSelective(ChurchMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	List<ChurchMember> selectByExample(ChurchMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	ChurchMember selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int updateByExampleSelective(@Param("record") ChurchMember record,
			@Param("example") ChurchMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int updateByExample(@Param("record") ChurchMember record,
			@Param("example") ChurchMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int updateByPrimaryKeySelective(ChurchMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	int updateByPrimaryKey(ChurchMember record);

	List<ChurchMember> selectList(Map<String,Object> record);
	
	int selectListCount(Map<String,Object> record);
}