package com.escape.dao;

import com.escape.model.Lotto;
import com.escape.model.LottoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LottoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int countByExample(LottoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int deleteByExample(LottoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int deleteByPrimaryKey(Integer round);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int insert(Lotto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int insertSelective(Lotto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    List<Lotto> selectByExample(LottoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    Lotto selectByPrimaryKey(Integer round);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int updateByExampleSelective(@Param("record") Lotto record, @Param("example") LottoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int updateByExample(@Param("record") Lotto record, @Param("example") LottoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int updateByPrimaryKeySelective(Lotto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lotto
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    int updateByPrimaryKey(Lotto record);
}