package com.escape.dao;

import com.escape.model.NhnCategory;
import com.escape.model.NhnCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NhnCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int countByExample(NhnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int deleteByExample(NhnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int insert(NhnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int insertSelective(NhnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    List<NhnCategory> selectByExample(NhnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    NhnCategory selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByExampleSelective(@Param("record") NhnCategory record, @Param("example") NhnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByExample(@Param("record") NhnCategory record, @Param("example") NhnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByPrimaryKeySelective(NhnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_category
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByPrimaryKey(NhnCategory record);
}