package com.escape.dao;

import com.escape.model.NhnRankWeek;
import com.escape.model.NhnRankWeekExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NhnRankWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int countByExample(NhnRankWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int deleteByExample(NhnRankWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int insert(NhnRankWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int insertSelective(NhnRankWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    List<NhnRankWeek> selectByExample(NhnRankWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    NhnRankWeek selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByExampleSelective(@Param("record") NhnRankWeek record, @Param("example") NhnRankWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByExample(@Param("record") NhnRankWeek record, @Param("example") NhnRankWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByPrimaryKeySelective(NhnRankWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_week
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByPrimaryKey(NhnRankWeek record);
}