package com.escape.dao;

import com.escape.model.NhnRankMonth;
import com.escape.model.NhnRankMonthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NhnRankMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int countByExample(NhnRankMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int deleteByExample(NhnRankMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int insert(NhnRankMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int insertSelective(NhnRankMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    List<NhnRankMonth> selectByExample(NhnRankMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    NhnRankMonth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByExampleSelective(@Param("record") NhnRankMonth record, @Param("example") NhnRankMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByExample(@Param("record") NhnRankMonth record, @Param("example") NhnRankMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByPrimaryKeySelective(NhnRankMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_rank_month
     *
     * @mbggenerated Fri Jun 28 15:07:30 KST 2019
     */
    int updateByPrimaryKey(NhnRankMonth record);
}