package com.escape.dao;

import com.escape.model.NhnTimeDimension;
import com.escape.model.NhnTimeDimensionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NhnTimeDimensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int countByExample(NhnTimeDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int deleteByExample(NhnTimeDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int deleteByPrimaryKey(String dimType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int insert(NhnTimeDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int insertSelective(NhnTimeDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    List<NhnTimeDimension> selectByExample(NhnTimeDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    NhnTimeDimension selectByPrimaryKey(String dimType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByExampleSelective(@Param("record") NhnTimeDimension record, @Param("example") NhnTimeDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByExample(@Param("record") NhnTimeDimension record, @Param("example") NhnTimeDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByPrimaryKeySelective(NhnTimeDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhn_time_dimension
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    int updateByPrimaryKey(NhnTimeDimension record);
}