package com.escape.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChurchMemberExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public ChurchMemberExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andChurchNameIsNull() {
			addCriterion("CHURCH_NAME is null");
			return (Criteria) this;
		}

		public Criteria andChurchNameIsNotNull() {
			addCriterion("CHURCH_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andChurchNameEqualTo(String value) {
			addCriterion("CHURCH_NAME =", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameNotEqualTo(String value) {
			addCriterion("CHURCH_NAME <>", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameGreaterThan(String value) {
			addCriterion("CHURCH_NAME >", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHURCH_NAME >=", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameLessThan(String value) {
			addCriterion("CHURCH_NAME <", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameLessThanOrEqualTo(String value) {
			addCriterion("CHURCH_NAME <=", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameLike(String value) {
			addCriterion("CHURCH_NAME like", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameNotLike(String value) {
			addCriterion("CHURCH_NAME not like", value, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameIn(List<String> values) {
			addCriterion("CHURCH_NAME in", values, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameNotIn(List<String> values) {
			addCriterion("CHURCH_NAME not in", values, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameBetween(String value1, String value2) {
			addCriterion("CHURCH_NAME between", value1, value2, "churchName");
			return (Criteria) this;
		}

		public Criteria andChurchNameNotBetween(String value1, String value2) {
			addCriterion("CHURCH_NAME not between", value1, value2,
					"churchName");
			return (Criteria) this;
		}

		public Criteria andChurchRootIsNull() {
			addCriterion("CHURCH_ROOT is null");
			return (Criteria) this;
		}

		public Criteria andChurchRootIsNotNull() {
			addCriterion("CHURCH_ROOT is not null");
			return (Criteria) this;
		}

		public Criteria andChurchRootEqualTo(String value) {
			addCriterion("CHURCH_ROOT =", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootNotEqualTo(String value) {
			addCriterion("CHURCH_ROOT <>", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootGreaterThan(String value) {
			addCriterion("CHURCH_ROOT >", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootGreaterThanOrEqualTo(String value) {
			addCriterion("CHURCH_ROOT >=", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootLessThan(String value) {
			addCriterion("CHURCH_ROOT <", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootLessThanOrEqualTo(String value) {
			addCriterion("CHURCH_ROOT <=", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootLike(String value) {
			addCriterion("CHURCH_ROOT like", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootNotLike(String value) {
			addCriterion("CHURCH_ROOT not like", value, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootIn(List<String> values) {
			addCriterion("CHURCH_ROOT in", values, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootNotIn(List<String> values) {
			addCriterion("CHURCH_ROOT not in", values, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootBetween(String value1, String value2) {
			addCriterion("CHURCH_ROOT between", value1, value2, "churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchRootNotBetween(String value1, String value2) {
			addCriterion("CHURCH_ROOT not between", value1, value2,
					"churchRoot");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryIsNull() {
			addCriterion("CHURCH_CATEGORY is null");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryIsNotNull() {
			addCriterion("CHURCH_CATEGORY is not null");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryEqualTo(String value) {
			addCriterion("CHURCH_CATEGORY =", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryNotEqualTo(String value) {
			addCriterion("CHURCH_CATEGORY <>", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryGreaterThan(String value) {
			addCriterion("CHURCH_CATEGORY >", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("CHURCH_CATEGORY >=", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryLessThan(String value) {
			addCriterion("CHURCH_CATEGORY <", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryLessThanOrEqualTo(String value) {
			addCriterion("CHURCH_CATEGORY <=", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryLike(String value) {
			addCriterion("CHURCH_CATEGORY like", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryNotLike(String value) {
			addCriterion("CHURCH_CATEGORY not like", value, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryIn(List<String> values) {
			addCriterion("CHURCH_CATEGORY in", values, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryNotIn(List<String> values) {
			addCriterion("CHURCH_CATEGORY not in", values, "churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryBetween(String value1, String value2) {
			addCriterion("CHURCH_CATEGORY between", value1, value2,
					"churchCategory");
			return (Criteria) this;
		}

		public Criteria andChurchCategoryNotBetween(String value1, String value2) {
			addCriterion("CHURCH_CATEGORY not between", value1, value2,
					"churchCategory");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnIsNull() {
			addCriterion("SEND_EMAIL_YN is null");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnIsNotNull() {
			addCriterion("SEND_EMAIL_YN is not null");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnEqualTo(String value) {
			addCriterion("SEND_EMAIL_YN =", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnNotEqualTo(String value) {
			addCriterion("SEND_EMAIL_YN <>", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnGreaterThan(String value) {
			addCriterion("SEND_EMAIL_YN >", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnGreaterThanOrEqualTo(String value) {
			addCriterion("SEND_EMAIL_YN >=", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnLessThan(String value) {
			addCriterion("SEND_EMAIL_YN <", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnLessThanOrEqualTo(String value) {
			addCriterion("SEND_EMAIL_YN <=", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnLike(String value) {
			addCriterion("SEND_EMAIL_YN like", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnNotLike(String value) {
			addCriterion("SEND_EMAIL_YN not like", value, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnIn(List<String> values) {
			addCriterion("SEND_EMAIL_YN in", values, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnNotIn(List<String> values) {
			addCriterion("SEND_EMAIL_YN not in", values, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnBetween(String value1, String value2) {
			addCriterion("SEND_EMAIL_YN between", value1, value2, "sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendEmailYnNotBetween(String value1, String value2) {
			addCriterion("SEND_EMAIL_YN not between", value1, value2,
					"sendEmailYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnIsNull() {
			addCriterion("SEND_ZC_YN is null");
			return (Criteria) this;
		}

		public Criteria andSendZcYnIsNotNull() {
			addCriterion("SEND_ZC_YN is not null");
			return (Criteria) this;
		}

		public Criteria andSendZcYnEqualTo(String value) {
			addCriterion("SEND_ZC_YN =", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnNotEqualTo(String value) {
			addCriterion("SEND_ZC_YN <>", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnGreaterThan(String value) {
			addCriterion("SEND_ZC_YN >", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnGreaterThanOrEqualTo(String value) {
			addCriterion("SEND_ZC_YN >=", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnLessThan(String value) {
			addCriterion("SEND_ZC_YN <", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnLessThanOrEqualTo(String value) {
			addCriterion("SEND_ZC_YN <=", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnLike(String value) {
			addCriterion("SEND_ZC_YN like", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnNotLike(String value) {
			addCriterion("SEND_ZC_YN not like", value, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnIn(List<String> values) {
			addCriterion("SEND_ZC_YN in", values, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnNotIn(List<String> values) {
			addCriterion("SEND_ZC_YN not in", values, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnBetween(String value1, String value2) {
			addCriterion("SEND_ZC_YN between", value1, value2, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andSendZcYnNotBetween(String value1, String value2) {
			addCriterion("SEND_ZC_YN not between", value1, value2, "sendZcYn");
			return (Criteria) this;
		}

		public Criteria andDelYnIsNull() {
			addCriterion("DEL_YN is null");
			return (Criteria) this;
		}

		public Criteria andDelYnIsNotNull() {
			addCriterion("DEL_YN is not null");
			return (Criteria) this;
		}

		public Criteria andDelYnEqualTo(String value) {
			addCriterion("DEL_YN =", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnNotEqualTo(String value) {
			addCriterion("DEL_YN <>", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnGreaterThan(String value) {
			addCriterion("DEL_YN >", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnGreaterThanOrEqualTo(String value) {
			addCriterion("DEL_YN >=", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnLessThan(String value) {
			addCriterion("DEL_YN <", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnLessThanOrEqualTo(String value) {
			addCriterion("DEL_YN <=", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnLike(String value) {
			addCriterion("DEL_YN like", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnNotLike(String value) {
			addCriterion("DEL_YN not like", value, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnIn(List<String> values) {
			addCriterion("DEL_YN in", values, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnNotIn(List<String> values) {
			addCriterion("DEL_YN not in", values, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnBetween(String value1, String value2) {
			addCriterion("DEL_YN between", value1, value2, "delYn");
			return (Criteria) this;
		}

		public Criteria andDelYnNotBetween(String value1, String value2) {
			addCriterion("DEL_YN not between", value1, value2, "delYn");
			return (Criteria) this;
		}

		public Criteria andInsDateIsNull() {
			addCriterion("INS_DATE is null");
			return (Criteria) this;
		}

		public Criteria andInsDateIsNotNull() {
			addCriterion("INS_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andInsDateEqualTo(Date value) {
			addCriterion("INS_DATE =", value, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateNotEqualTo(Date value) {
			addCriterion("INS_DATE <>", value, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateGreaterThan(Date value) {
			addCriterion("INS_DATE >", value, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateGreaterThanOrEqualTo(Date value) {
			addCriterion("INS_DATE >=", value, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateLessThan(Date value) {
			addCriterion("INS_DATE <", value, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateLessThanOrEqualTo(Date value) {
			addCriterion("INS_DATE <=", value, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateIn(List<Date> values) {
			addCriterion("INS_DATE in", values, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateNotIn(List<Date> values) {
			addCriterion("INS_DATE not in", values, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateBetween(Date value1, Date value2) {
			addCriterion("INS_DATE between", value1, value2, "insDate");
			return (Criteria) this;
		}

		public Criteria andInsDateNotBetween(Date value1, Date value2) {
			addCriterion("INS_DATE not between", value1, value2, "insDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateIsNull() {
			addCriterion("UPD_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdDateIsNotNull() {
			addCriterion("UPD_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdDateEqualTo(Date value) {
			addCriterion("UPD_DATE =", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateNotEqualTo(Date value) {
			addCriterion("UPD_DATE <>", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateGreaterThan(Date value) {
			addCriterion("UPD_DATE >", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPD_DATE >=", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateLessThan(Date value) {
			addCriterion("UPD_DATE <", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateLessThanOrEqualTo(Date value) {
			addCriterion("UPD_DATE <=", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateIn(List<Date> values) {
			addCriterion("UPD_DATE in", values, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateNotIn(List<Date> values) {
			addCriterion("UPD_DATE not in", values, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateBetween(Date value1, Date value2) {
			addCriterion("UPD_DATE between", value1, value2, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateNotBetween(Date value1, Date value2) {
			addCriterion("UPD_DATE not between", value1, value2, "updDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table church_member
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table church_member
     *
     * @mbggenerated do_not_delete_during_merge Tue May 28 17:06:22 KST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}