package com.escape.model;

import java.util.Date;

public class ChurchMember {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.ID
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.EMAIL
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.NAME
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.CHURCH_NAME
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String churchName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.CHURCH_ROOT
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String churchRoot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.CHURCH_CATEGORY
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String churchCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.SEND_EMAIL_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String sendEmailYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.SEND_ZC_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String sendZcYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.DEL_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private String delYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.INS_DATE
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private Date insDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column church_member.UPD_DATE
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	private Date updDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.ID
	 * @return  the value of church_member.ID
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.ID
	 * @param id  the value for church_member.ID
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.EMAIL
	 * @return  the value of church_member.EMAIL
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.EMAIL
	 * @param email  the value for church_member.EMAIL
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.NAME
	 * @return  the value of church_member.NAME
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.NAME
	 * @param name  the value for church_member.NAME
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.CHURCH_NAME
	 * @return  the value of church_member.CHURCH_NAME
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getChurchName() {
		return churchName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.CHURCH_NAME
	 * @param churchName  the value for church_member.CHURCH_NAME
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setChurchName(String churchName) {
		this.churchName = churchName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.CHURCH_ROOT
	 * @return  the value of church_member.CHURCH_ROOT
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getChurchRoot() {
		return churchRoot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.CHURCH_ROOT
	 * @param churchRoot  the value for church_member.CHURCH_ROOT
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setChurchRoot(String churchRoot) {
		this.churchRoot = churchRoot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.CHURCH_CATEGORY
	 * @return  the value of church_member.CHURCH_CATEGORY
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getChurchCategory() {
		return churchCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.CHURCH_CATEGORY
	 * @param churchCategory  the value for church_member.CHURCH_CATEGORY
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setChurchCategory(String churchCategory) {
		this.churchCategory = churchCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.SEND_EMAIL_YN
	 * @return  the value of church_member.SEND_EMAIL_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getSendEmailYn() {
		return sendEmailYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.SEND_EMAIL_YN
	 * @param sendEmailYn  the value for church_member.SEND_EMAIL_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setSendEmailYn(String sendEmailYn) {
		this.sendEmailYn = sendEmailYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.SEND_ZC_YN
	 * @return  the value of church_member.SEND_ZC_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getSendZcYn() {
		return sendZcYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.SEND_ZC_YN
	 * @param sendZcYn  the value for church_member.SEND_ZC_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setSendZcYn(String sendZcYn) {
		this.sendZcYn = sendZcYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.DEL_YN
	 * @return  the value of church_member.DEL_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public String getDelYn() {
		return delYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.DEL_YN
	 * @param delYn  the value for church_member.DEL_YN
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.INS_DATE
	 * @return  the value of church_member.INS_DATE
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public Date getInsDate() {
		return insDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.INS_DATE
	 * @param insDate  the value for church_member.INS_DATE
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column church_member.UPD_DATE
	 * @return  the value of church_member.UPD_DATE
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public Date getUpdDate() {
		return updDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column church_member.UPD_DATE
	 * @param updDate  the value for church_member.UPD_DATE
	 * @mbggenerated  Fri Jun 28 11:01:20 KST 2019
	 */
	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}
}