package com.escape.model;

public class Lotto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.ROUND
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.LOTTERY_DAY
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private String lotteryDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.WIN_NUM1
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer winNum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.WIN_NUM2
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer winNum2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.WIN_NUM3
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer winNum3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.WIN_NUM4
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer winNum4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.WIN_NUM5
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer winNum5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.WIN_NUM6
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer winNum6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.BONUS_NUM
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private Integer bonusNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lotto.INS_DATE
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    private String insDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.ROUND
     *
     * @return the value of lotto.ROUND
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.ROUND
     *
     * @param round the value for lotto.ROUND
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.LOTTERY_DAY
     *
     * @return the value of lotto.LOTTERY_DAY
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public String getLotteryDay() {
        return lotteryDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.LOTTERY_DAY
     *
     * @param lotteryDay the value for lotto.LOTTERY_DAY
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setLotteryDay(String lotteryDay) {
        this.lotteryDay = lotteryDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.WIN_NUM1
     *
     * @return the value of lotto.WIN_NUM1
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getWinNum1() {
        return winNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.WIN_NUM1
     *
     * @param winNum1 the value for lotto.WIN_NUM1
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setWinNum1(Integer winNum1) {
        this.winNum1 = winNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.WIN_NUM2
     *
     * @return the value of lotto.WIN_NUM2
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getWinNum2() {
        return winNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.WIN_NUM2
     *
     * @param winNum2 the value for lotto.WIN_NUM2
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setWinNum2(Integer winNum2) {
        this.winNum2 = winNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.WIN_NUM3
     *
     * @return the value of lotto.WIN_NUM3
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getWinNum3() {
        return winNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.WIN_NUM3
     *
     * @param winNum3 the value for lotto.WIN_NUM3
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setWinNum3(Integer winNum3) {
        this.winNum3 = winNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.WIN_NUM4
     *
     * @return the value of lotto.WIN_NUM4
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getWinNum4() {
        return winNum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.WIN_NUM4
     *
     * @param winNum4 the value for lotto.WIN_NUM4
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setWinNum4(Integer winNum4) {
        this.winNum4 = winNum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.WIN_NUM5
     *
     * @return the value of lotto.WIN_NUM5
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getWinNum5() {
        return winNum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.WIN_NUM5
     *
     * @param winNum5 the value for lotto.WIN_NUM5
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setWinNum5(Integer winNum5) {
        this.winNum5 = winNum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.WIN_NUM6
     *
     * @return the value of lotto.WIN_NUM6
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getWinNum6() {
        return winNum6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.WIN_NUM6
     *
     * @param winNum6 the value for lotto.WIN_NUM6
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setWinNum6(Integer winNum6) {
        this.winNum6 = winNum6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.BONUS_NUM
     *
     * @return the value of lotto.BONUS_NUM
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public Integer getBonusNum() {
        return bonusNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.BONUS_NUM
     *
     * @param bonusNum the value for lotto.BONUS_NUM
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setBonusNum(Integer bonusNum) {
        this.bonusNum = bonusNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lotto.INS_DATE
     *
     * @return the value of lotto.INS_DATE
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public String getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lotto.INS_DATE
     *
     * @param insDate the value for lotto.INS_DATE
     *
     * @mbggenerated Fri Jul 12 15:54:40 KST 2019
     */
    public void setInsDate(String insDate) {
        this.insDate = insDate;
    }
}