package com.escape.model;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ID
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.NAME
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.AGE
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ID
     *
     * @return the value of member.ID
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ID
     *
     * @param id the value for member.ID
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.NAME
     *
     * @return the value of member.NAME
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.NAME
     *
     * @param name the value for member.NAME
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.AGE
     *
     * @return the value of member.AGE
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.AGE
     *
     * @param age the value for member.AGE
     *
     * @mbggenerated Fri May 24 11:53:32 KST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}