package com.escape.model;

public class NhnRankDate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_rank_date.ID
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_rank_date.DATETIME
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    private String datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_rank_date.TITLE
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_rank_date.SEQ
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_rank_date.CID
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_rank_date.INS_DATE
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    private String insDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_rank_date.ID
     *
     * @return the value of nhn_rank_date.ID
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_rank_date.ID
     *
     * @param id the value for nhn_rank_date.ID
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_rank_date.DATETIME
     *
     * @return the value of nhn_rank_date.DATETIME
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_rank_date.DATETIME
     *
     * @param datetime the value for nhn_rank_date.DATETIME
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_rank_date.TITLE
     *
     * @return the value of nhn_rank_date.TITLE
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_rank_date.TITLE
     *
     * @param title the value for nhn_rank_date.TITLE
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_rank_date.SEQ
     *
     * @return the value of nhn_rank_date.SEQ
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_rank_date.SEQ
     *
     * @param seq the value for nhn_rank_date.SEQ
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_rank_date.CID
     *
     * @return the value of nhn_rank_date.CID
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_rank_date.CID
     *
     * @param cid the value for nhn_rank_date.CID
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_rank_date.INS_DATE
     *
     * @return the value of nhn_rank_date.INS_DATE
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public String getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_rank_date.INS_DATE
     *
     * @param insDate the value for nhn_rank_date.INS_DATE
     *
     * @mbggenerated Fri Jun 28 14:32:32 KST 2019
     */
    public void setInsDate(String insDate) {
        this.insDate = insDate;
    }
}