package com.escape.model;

import java.util.Date;

public class NhnTimeDimension {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_time_dimension.DIM_TYPE
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    private String dimType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_time_dimension.DIM_NAME
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    private String dimName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhn_time_dimension.INS_DATE
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    private Date insDate = new Date();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_time_dimension.DIM_TYPE
     *
     * @return the value of nhn_time_dimension.DIM_TYPE
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    public String getDimType() {
        return dimType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_time_dimension.DIM_TYPE
     *
     * @param dimType the value for nhn_time_dimension.DIM_TYPE
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    public void setDimType(String dimType) {
        this.dimType = dimType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_time_dimension.DIM_NAME
     *
     * @return the value of nhn_time_dimension.DIM_NAME
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    public String getDimName() {
        return dimName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_time_dimension.DIM_NAME
     *
     * @param dimName the value for nhn_time_dimension.DIM_NAME
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    public void setDimName(String dimName) {
        this.dimName = dimName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhn_time_dimension.INS_DATE
     *
     * @return the value of nhn_time_dimension.INS_DATE
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    public Date getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhn_time_dimension.INS_DATE
     *
     * @param insDate the value for nhn_time_dimension.INS_DATE
     *
     * @mbggenerated Fri Jun 28 11:03:55 KST 2019
     */
    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }
}